name: ecommerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.0
  internet_connection_checker: ^0.0.1+2
  http: ^1.2.2
  shared_preferences: ^2.0.8
  rxdart: ^0.28.0
  bloc_test: ^9.1.7
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/nike.jpg
    - assets/images/splash.jpg

  fonts:
    - family: Caveat Brush
      fonts:
        - asset: fonts/CaveatBrush-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
